services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - /home/ubuntu/Devchat/.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=devchat
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - dev-chat-network

  dev-chat-frontend:
    image: limkanghyun/dev-chat-frontend:latest
    networks:
      - dev-chat-network

  dev-chat-backend-blue:
    image: limkanghyun/dev-chat-backend:latest
    container_name: dev-chat-backend-blue
    env_file:
      - /home/ubuntu/Devchat/.env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - RDS_ENDPOINT=${RDS_ENDPOINT}
    networks:
      - dev-chat-network
      - redis-cluster_redis-net 

  dev-chat-backend-green:
    image: limkanghyun/dev-chat-backend:latest
    container_name: dev-chat-backend-green
    env_file:
      - /home/ubuntu/Devchat/.env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - RDS_ENDPOINT=${RDS_ENDPOINT}
    networks:
      - dev-chat-network
      - redis-cluster_redis-net 

  nginx_proxy:
    image: nginx:latest
    volumes:
      - ./deployment/nginx_proxy/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dev-chat-network

networks:
  dev-chat-network:
    driver: bridge
  redis-cluster_redis-net:
    external: true
    name: redis-sentinel_redis-net
