ALTER TABLE ai_review MODIFY COLUMN status ENUM('PENDING', 'SUCCESS', 'FAIL', 'SKIPPED') NOT NULL DEFAULT 'PENDING';
ALTER TABLE ai_review MODIFY COLUMN review_json LONGTEXT;
ALTER TABLE ai_review MODIFY COLUMN error_message TEXT;